class CatalogAgent:
    def run(self, step: dict) -> dict:
        context = step.get("context", {})
        sku = context.get("sku", "UNKNOWN-SKU")
        return {
            "agent": "catalog_agent",
            "status": "ok",
            "action": step.get("action"),
            "master_record": {
                "sku": sku,
                "title_master": f"Tracker {sku}",
                "description_master": "Draft description generated by CatalogAgent."
            }
        }
